# Generated by Django 3.2.6 on 2021-09-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_favoriterecipe_unique_recipefavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'default_related_name': 'shopping_cart',
            },
        ),
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={'default_related_name': 'favorites'},
        ),
        migrations.RemoveConstraint(
            model_name='favoriterecipe',
            name='unique_RecipeFavorite',
        ),
    ]
