# Generated by Django 3.2.6 on 2021-10-12 19:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_auto_20211002_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[(1, 'л'), (2, 'бутылка'), (3, 'зубчик'), (4, 'щепотка'), (5, 'пачка'), (6, 'пучок'), (7, 'банка'), (8, 'веточка'), (9, 'стакан'), (10, 'стручок'), (11, 'шт.'), (12, 'пласт'), (13, 'звездочка'), (14, 'кг'), (15, 'тушка'), (16, 'батон'), (17, 'упаковка'), (18, 'мл'), (19, 'пакетик'), (20, 'г'), (21, 'горсть'), (22, 'кусок'), (23, 'по вкусу'), (24, 'г.'), (25, 'стебель'), (26, 'ст. л.'), (27, 'капля'), (28, 'пакет'), (29, 'долька'), (30, 'ч. л.'), (31, 'лист')], max_length=200, verbose_name='Ед. измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Значение не может быть меньше 1')], verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Значение не может быть меньше 1')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
