# Generated by Django 3.2.6 on 2021-10-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211012_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[(1, 'л'), (2, 'бутылка'), (3, 'зубчик'), (4, 'щепотка'), (5, 'пачка'), (6, 'пучок'), (7, 'банка'), (8, 'веточка'), (9, 'стакан'), (10, 'кг'), (11, 'стручок'), (12, 'шт.'), (13, 'пласт'), (14, 'звездочка'), (15, 'тушка'), (16, 'батон'), (17, 'упаковка'), (18, 'мл'), (19, 'г'), (20, 'пакетик'), (21, 'горсть'), (22, 'кусок'), (23, 'по вкусу'), (24, 'г.'), (25, 'стебель'), (26, 'ст. л.'), (27, 'капля'), (28, 'пакет'), (29, 'долька'), (30, 'ч. л.'), (31, 'лист')], default=19, max_length=200, verbose_name='Ед. измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipe_images', verbose_name='Изображение'),
        ),
    ]
